# Generated by Django 4.0.4 on 2022-06-19 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childname', models.CharField(max_length=30, verbose_name="Ім'я дитини")),
                ('age', models.IntegerField(verbose_name='Вік дитини')),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дитина',
                'verbose_name_plural': 'Діти',
                'unique_together': {('childname', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Results_of_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers', models.IntegerField(verbose_name='Кількість правильних відповідей')),
                ('wrong_answers', models.IntegerField(verbose_name='Кількість неправильних відповідей')),
                ('success', models.BooleanField(verbose_name='Тестування успішне')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата тестування')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.child')),
            ],
            options={
                'verbose_name': 'Результат тестування',
                'verbose_name_plural': 'Результати тестувань',
            },
        ),
    ]
