# Generated by Django 4.0.4 on 2022-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_results_of_test_options_alter_child_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Вік дитини'),
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата народження'),
        ),
    ]
